# NB

In [ ]:
from sklearn.naive_bayes import 

In [38]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import numpy as np

In [39]:
class0_len = 1000
X0 = np.random.normal((0,1,2), (1,2,2), (class0_len,3))
y0 = [0]*class0_len

class1_len = 2000
X1 = np.random.normal((1,1,-1), (3,1,1), (class1_len, 3))
y1 = [1]*class1_len

In [40]:
X = np.concatenate((X0, X1))
y = y0+y1

In [41]:
X

array([[-0.54218028, -1.19485205,  3.54751326],
       [-0.0177535 ,  3.14272287,  0.64820635],
       [ 1.05888268, -5.05981115,  4.74095986],
       ...,
       [ 0.09622354,  0.48730279, -0.63095176],
       [-3.7561025 ,  3.81579069, -1.56810772],
       [ 4.97059808, -1.05728214, -0.9948339 ]])

In [42]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [43]:
gnb = GaussianNB()

In [44]:
gnb.fit(X_train, y_train)

GaussianNB()

In [45]:
gnb.score(X_train, y_train)

0.9191111111111111

In [46]:
gnb.score(X_val, y_val)

0.9146666666666666

# LDA

In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()

In [47]:
class0_len = 1000
X0 = np.random.multivariate_normal([1,2,-1], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class0_len)
y0 = [0]*class0_len

class1_len = 3000
X1 = np.random.multivariate_normal([1,1,0], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class1_len)
y1 = [1]*class1_len

In [48]:
X = np.concatenate((X0, X1))
y = y0+y1

In [49]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [50]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb.score(X_val, y_val)

0.868

In [51]:
gnb.score(X_train, y_train)

0.8596666666666667

In [52]:
clf.fit(X_train, y_train)
clf.score(X_val, y_val)

0.986

In [53]:
clf.score(X_train, y_train)

0.9883333333333333

In [54]:
np.cov(X0.T)

array([[0.9964345 , 0.90223342, 0.89855967],
       [0.90223342, 0.99431488, 0.8965978 ],
       [0.89855967, 0.8965978 , 0.99000399]])

In [55]:
np.cov(X1.T)

array([[1.03108132, 0.91785157, 0.90362482],
       [0.91785157, 1.01264349, 0.89891187],
       [0.90362482, 0.89891187, 0.98633913]])

# QDA

In [24]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
clf = QuadraticDiscriminantAnalysis()

In [56]:
class0_len = 1000
X0 = np.random.multivariate_normal([1,2,0], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class0_len)
y0 = [0]*class0_len

class1_len = 3000
X1 = np.random.multivariate_normal([1,1,0], np.array([[1, 0.4, 0.2], [0.4, 1, 0.8], [0.2, 0.8, 1]]), size=class1_len)
y1 = [1]*class1_len

In [57]:
X = np.concatenate((X0, X1))
y = y0+y1

In [58]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [59]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb.score(X_val, y_val)

0.781

In [60]:
gnb.score(X_train, y_train)

0.779

In [61]:
clf.fit(X_train, y_train)
clf.score(X_val, y_val)

0.91

In [62]:
clf.score(X_train, y_train)

0.9016666666666666

In [63]:
clf_linear = LinearDiscriminantAnalysis()

In [64]:
clf_linear.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [65]:
clf_linear.score(X_val, y_val)

0.858

In [66]:
clf_linear.score(X_train, y_train)

0.8626666666666667